######################################################################
# Automatically generated by qmake (1.04a) Wed Feb 12 08:47:43 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += xmlwriter.h
SOURCES += main.cpp xmlwriter.cpp

TARGET = xmlwriter
