######################################################################
# Automatically generated by qmake (1.04a) Wed Feb 12 08:47:43 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += modulelibraryitem.h blockmodel.h inputblockmodel.h outputblockmodel.h muxmodel.h functionblockmodel.h coremodel.h cpumodel.h codemanager.h pinvector.h pin.h
SOURCES += main.cpp

TARGET = main
